### ISSUE TITLE
Save compatibility

### ISSUE THREAD

**Issue by grit96** [itsapi/pycraft#103]
There is no compatibility for saves between miltiplayer and master. Perhaps we should add some, or at least a converter.

**Comment by olls** [comment]
Or just make it error nicely

**Comment by grit96** [comment]
should we store a save version in the meta and rely on that when opening the meta?

**Comment by olls** [comment]
Probably

**Comment by grit96** [comment]
Or perhaps we should go back to checking the whole map on load?

**Comment by olls** [comment]
No, I don't like that idea. This is not that big of a problem, once we merge multiplayer it will hardly ever happen. I think just recording the save version with the save and checking we can load that version is good enough.

**Comment by grit96** [comment]
This will actually be quite messy because the message will have to travel from `saves.py` ==>

**Comment by olls** [comment]
Maybe we need a more robust system for sending errors from the back-end to the game loop
