### ISSUE TITLE
C Renderer on Master

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#108]
It would be nice to backport the `neopixels` C renderer to the `master` branch.

**Comment by grit96** [comment]
Not finished yet...

**Comment by olls** [comment]
How would we go about structuring this in Git? Ideally the `c-renderer` would be in it's own branch with `neopixels` branched off, but the history would be wrong if we did that now.

**Comment by grit96** [comment]
We could merge neopixels into master from before we started the C renderer
as that part was working. Then we leave the C renderer in it's own branch
with the C neopixels off that

**Comment by olls** [comment]
Good point

**Comment by grit96** [comment]
We are probably ready to do this now

**Comment by olls** [comment]
#115
