### ISSUE TITLE
Optimising C Renderer

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#109]
Currently the C renderer is no different from the Python renderer in terms of speed (as far as I can tell...)

**Comment by grit96** [comment]
It's quicker driving the neopixels on a Pi definitely

**Comment by olls** [comment]
OK, on my computer it almost seems slower... Would be good to optimise it anyway!

**Comment by olls** [comment]
It is definitely slower on my PC. There seems to be a bug in the differential output though, because it is reprinting more blocks than the python renderer on average.

**Comment by grit96** [comment]
We seem to have a memory leak somewhere as it gets very slow to open the pause menu or quit the game.

**Comment by olls** [comment]
This is useful to know: https://wiki.python.org/moin/TimeComplexity
