### ISSUE TITLE
Issue with Python3 (3.5.1) and running on Mac OS

### ISSUE THREAD

**Issue by jthomas124124** [itsapi/pycraft#111]
On Mac OS with version 3.5.1 of Python, pycraft just seems to scroll down forever creating the occasional blocks of colour on the screen and duplicating the crafting and inventory labels
<img width="593" alt="screen shot 2016-06-08 at 17 56 20" src="https://cloud.githubusercontent.com/assets/6472928/15902968/60873260-2da2-11e6-8277-d31313087469.png">

**Comment by olls** [comment]
Have you tried making the terminal taller, it might not have space to draw it.

**Comment by grit96** [comment]
We do need to support small windows better, see #43
