### ISSUE TITLE
Issue trying to enter the game with gravity enabled

### ISSUE THREAD

**Issue by Yardanico** [itsapi/pycraft#121]
Lubuntu 16.04, Python 3.5.2 (default, Jul  5 2016, 12:43:10)
While loading the save (or creating the new one) - https://paste.pound-python.org/show/9c0IqRtpAxggPa7LsXT8/

If I try to enter the game without gravity or flight enabled - there's a strange thing: slowly moving blue blocks (water I think) - as I would dig into terrain..

**Comment by TiberiumPY** [comment]
Ctrl+C after strange blue blocks gives this:

> File "/home/tiber/bench/pycraft/render.py", line 58, in render_map
    bk_objects, sky_colour, day, lights, settings.get('fancy_lights'))

**Comment by TiberiumPY** [comment]
Asciinema rec: [https://asciinema.org/a/e7gd8qoagrhqwdgz1kuwzxl0c

**Comment by grit96** [comment]
The recording might be related to #43, try increasing the terminal window size.

**Comment by TiberiumPY** [comment]
@grit96 yes, it worked

**Comment by TiberiumPY** [comment]
@grit96 by the way, your game works just perfectly on pypy3.5

**Comment by grit96** [comment]
That's good to know, thanks for testing it.

The gravity feature is very experimental and quite buggy (as you've found out). The RecursionError you got is because of the size of the map and the way we are calculating the gravity currently.

**Comment by TiberiumPY** [comment]
@grit96 you can add some benchmarks in future :+1:

**Comment by TiberiumPY** [comment]
@grit96 like render benchmark and terrain generation
