### ISSUE TITLE
CLS

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#13]
The current `CLS` variable in `console.py` is `chr(27) + '[2J'`, which is equivalent to the `clear` command in bash, which just scrolls the console down (at least in `gnome-terminal`). The code `\033c` actually clears the terminal, which makes the game much smoother. Unfortunately this conflicts with something in the program, probably the `colors` module, and causes like: `;37m` to be printed out in the middle of the terminal. There is lots of info [here](http://superuser.com/questions/122911/bash-reset-and-clear-commands) but I can't find one which works.

**Comment by grit96** [comment]
Made irrelevant by 213b0547be60501a663e1e779fd8d28fca27be66
