### ISSUE TITLE
Continious Scroll problem

### ISSUE THREAD

**Issue by hubbyist** [itsapi/pycraft#142]
I am experiencing similar issue as  #13 on linux mint 18.3. Tried both in terminal and terminator. Inventory is 3 lines and map is continuously scrolling.

**Comment by olls** [comment]
Hey, sorry for the late response!  

This is usually caused by the terminal window being shorter than the game's rendered view.  If you increase your terminal height, or decrease the game height (through the settings window), it should fix it.
