### ISSUE TITLE
Game is dont work.

### ISSUE THREAD

**Issue by pixaxeofpixie** [itsapi/pycraft#152]
I launch main.py in Python Launcher.After that i enter my name and create a world.Im enter in world an THIS HAPPENING.Every time.
computer-iMac 2010
os-MacOSX High Sierra.

[screenshot1.zip](https://github.com/itsapi/pycraft/files/5011916/screenshot1.zip)
[screenshot2.zip](https://github.com/itsapi/pycraft/files/5011917/screenshot2.zip)

**Comment by pixaxeofpixie** [comment]
please help me.

**Comment by lusantisuper** [comment]
I'm running Linux (ManjaroOS 20.1).
I'm having the same problem, probably it's because the terminal is updating every frame and not removing the old ones. Only writing below the previews frame!

**Comment by olls** [comment]
This can happen if your terminal is too small.  In your screenshots it looks like the terminal might be too short?

**Comment by olls** [comment]
Please re-open if you are still having an issue.
