### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by grit96** [itsapi/pycraft#24]
In order to do this:

- [x] rewrite save handling to use chunking in memory #23
- [x] write a server program to handle distributing chunks to clients, keeping track of player locations (we will need something similar for keeping track of mobs)
- [x] modify client code to accept chunks from the server and render other players
- [x] combine server and client code #36

**Comment by grit96** [comment]
[This](http://stackoverflow.com/questions/10605161/data-lost-on-receiver-side-in-python-socket-programming) may help with our data loss problem.

**Comment by olls** [comment]
Progress report:

- We have the ability to host a game from within a save, and you can connect to it externally.
- There are still occasional problems with data loss.

Still todo:

- [ ] Rebroadcasting events from server to all clients.
- [ ] Showing other clients.
- [ ] Fixing bugs, and optimising to reduce overhead/lag.
- [ ] ...

**Comment by grit96** [comment]
Need to broadcast login and logout so only logged in players are visible. Also other players do not re-render if they move near you until you move (or the sun moves).

**Comment by olls** [comment]
We should probably implement locking when calling functions outside of the threads. It might be a problem when more players connect.

**Comment by olls** [comment]
Why are we still loesing bits of the data? TCP should be reliable!

**Comment by olls** [comment]
Locking did not make much difference: 06a8ac0a3fb92402ea7b57ad98725101f1ae17c5
