### ISSUE TITLE
Show selector in different colour in not selected grid

### ISSUE THREAD

**Issue by grit96** [itsapi/pycraft#28]
Mentioned in #25 and #21, to allow placing and breaking blocks while in crafting menu the inv sel should be a different colour.

**Comment by grit96** [comment]
Why should we allow breaking and placing blocks when focused on crafting grid if we don't allow crafting when focused on the inv?

**Comment by olls** [comment]
I don't think we should allow breaking and placing blocks when focused on crafting grid, but showing it i a different colour is better than not showing it.
