### ISSUE TITLE
Loading from the save file on server

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#34]
The `load_chunks` method in both `RemoteServer` and `Server` assume the chunks passed are not already loaded in memory, this is checked in the main loop. But now the server has different chunks loaded in memory to the client, so the server might have chunks already loaded in memory, but it will always reload them when [`load_chunks`](https://github.com/itsapi/pycraft/blob/multiplayer/server.py#L179) is called externally.

I'm not sure what would be the best way to fix this. If we add checks to the `Server.load_chunks` function then it will be doing the checks twice unnecessarily on the host, but we need to do the checks on the clients and the server.

**Comment by grit96** [comment]
If it's done in load_chunks can it be removed from the main loop?

**Comment by olls** [comment]
Yes, that should work

**Comment by grit96** [comment]
Did we fix this?

**Comment by olls** [comment]
I think so, Needs checking again though

**Comment by grit96** [comment]
Migrated to #36
