### ISSUE TITLE
Network Communication Buggy

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#39]
It keeps missing bits! Why are we still losing bits of the data? TCP should be reliable!

From [Wikipedia](http://en.wikipedia.org/wiki/Transmission_Control_Protocol#Network_function):
> TCP detects these problems, requests retransmission of lost data, rearranges out-of-order data, and even helps minimize network congestion to reduce the occurrence of the other problems. If the data still remains undelivered, its source is notified of this failure

[TCP Definition](http://www.linfo.org/tcp.html):
> TCP uses error correction and data stream control techniques to ensure that packets to arrive at their intended destinations uncorrupted and in the correct sequence, thereby making the point-to-point connection virtually error-free. Packets are the most fundamental unit of data transmission on TCP/IP networks.

We need to figure out why it's not.

**Comment by grit96** [comment]
Fixed a lot of the issues f9fff6535cdefdf25b7b67744ee22a74bde04599

**Comment by grit96** [comment]
Still need to add resending of messages. We should determine
