### ISSUE TITLE
Efficiency

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#61]
I think we should try to keep all the variables under control a bit more, especially in the main loop. We need to ensure we are not needlessly passing large amounts of data around, etc...

**Comment by olls** [comment]
This will also help us get the code under more control, and probably help us make it more extend-able.

**Comment by olls** [comment]
The Server class helps with the bigger ones, like map. It keeps them in one place.

Another thing that goes with this is to give a clearer definition of the types/format of the variables, lists, tuples...

**Comment by olls** [comment]
Also, maybe we shouldn't be running in a `while True` loop with no delay...

**Comment by grit96** [comment]
Yes
