### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by olls** [itsapi/pycraft#63]
[Pycraft](https://www.google.co.uk/search?q=pycraft) is a very common name, for many things, including lots of quite similar things...

How about 'Termcraft'?

**Comment by NDevox** [comment]
pixelcraft?

**Comment by grit96** [comment]
It looks like a number of other things have the name PixelCraft, perhaps something a little more unique would be better.

**Comment by NDevox** [comment]
Most are based around pixel art on minecraft though - I'd find it a more appropriate name for this type of project. 

Could also play off the 2D/platformer aspect. FlatCraft or PaperCraft or something similar.

**Comment by olls** [comment]
We chose Termcraft as it keeps the relation with Py**craft** and Mine**craft**, and also has the link with **term**, from **term**inal. It also seems to have few other uses, which is good.
