### ISSUE TITLE
Multiplayer bugs

### ISSUE THREAD

**Issue by grit96** [itsapi/pycraft#90]
- [x] chunk loading issues (we should try to resend after a timeout)
- [x] player characters disappearing (server keeps disappearing)
- [x] inventory sync issues (server gets a client's inventory)
- [x] server player teleports visually to client on client's view

**Comment by olls** [comment]
We will also need to think about terrain generation, the current version is assuming one player.

**Comment by grit96** [comment]
Still some problems with sockets not closing properly when the server closes and logs out all clients.
