### ISSUE TITLE
Tree generation isn't the same for the same seed

### ISSUE THREAD

**Issue by SullyJHF** [itsapi/pycraft#97]
I created two worlds, each generated with the same seed: 12345
All the trees that I encountered to the left seemed the same, however walking to the right there were a few trees missing in one/extra in the other.
These were created on two different machines both running chromeos with ubuntu trusty chroots.

**Comment by grit96** [comment]
Note: happens on master with one ARM chromebook and one Intel chromebook

**Comment by grit96** [comment]
Terrain generation has been completely rewritten in multiplayer.
